version: '3'

services:
  db:
    build:
      context: /Users/sukritirai/Documents/GitHub/full_stack_homework/myapp
      dockerfile: /Users/sukritirai/Documents/GitHub/full_stack_homework/Dockerfile
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  react-app:
    build:
      context: /Users/sukritirai/Documents/GitHub/full_stack_homework/myapp
      dockerfile: /Users/sukritirai/Documents/GitHub/full_stack_homework/myapp/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /Users/sukritirai/Documents/GitHub/full_stack_homework/myapp:/usr/src/app
    depends_on:
      - db

  flask-app:
    build:
      context: /Users/sukritirai/Documents/GitHub/full_stack_homework/backend
      dockerfile: /Users/sukritirai/Documents/GitHub/full_stack_homework/backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
